
---
- name: install php and mariadb
  hosts: dev,test,prod
  tasks:
  - name: install start
    yum:
      name:
      - php
      - mariadb
      state: present
- name: install dev
  hosts: dev
  tasks:
  - name: install tools
    yum:
      name:
      - '@Development Tools'
      state: present
  - name: update all
    yum:
      name:
      - '*'
      state: latest




